name: CI pipeline
run-name: Running the CI pipeline with ${{ github.actor }} changes
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:1.19.4-alpine3.17
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: make deps
      - name: Run Lint
        run: make lint